Teploobmen/Models/ErrorViewModel.cs
namespace Teploobmen.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Teploobmen/Models/HomeIndexViewModel.cs
using Teploobmen.Data;

namespace Teploobmen.Models
{
    public class HomeIndexViewModel
    {
        public Option? Option { get; set; }
        public List<Option> Options { get; set; }
    }
}

Teploobmen/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using System.Diagnostics;
using Teploobmen.Data;
using Teploobmen.Models;
using TeploobmenLibrary;

namespace labwork2_web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ApplicationContext _context;
        private int _userId;

        public HomeController(ILogger<HomeController> logger, ApplicationContext applicationContext)
        {
            _logger = logger;
            _context = applicationContext;
        }

        public override void OnActionExecuting(ActionExecutingContext context)
        {
            int.TryParse(User.FindFirst("Id")?.Value, out _userId);
        }

        [HttpPost]
        public IActionResult Result(TeploobmenInput input)
        {
            //Сохранение варианта
            if (!string.IsNullOrEmpty(input.Name))
            {
                var existOption = _context.Options.FirstOrDefault(x => x.Name == input.Name);

                if (existOption != null)
                {
                    // Обновление варианта
                    existOption.H = input.H;
                    existOption.t1 = input.t1;
                    existOption.T = input.T;
                    existOption.w = input.w;
                    existOption.C = input.C;
                    existOption.Gm = input.Gm;
                    existOption.Cm = input.Cm;
                    existOption.d = input.d;
                    existOption.a = input.a;

                    _context.Options.Update(existOption);
                    _context.SaveChanges();
                }
                else
                {
                    //добавление варианта
                    var Option = new Option
                    {
                        Name = input.Name,
                        H = input.H,
                        t1 = input.t1,
                        T = input.T,
                        w = input.w,
                        C = input.C,
                        Gm = input.Gm,
                        Cm = input.Cm,
                        d = input.d,
                        a = input.a,
                        UserId = _userId,
                        CreatedAt = DateTime.Now
                    };

                    _context.Options.Add(Option);
                    _context.SaveChanges();
                }
            }
            //Выполнение расчёта
            var lib = new TeploobmenCalc(input);
            var result = lib.calc();
            if (ModelState.IsValid)
                return View(result);
            TempData["message"] = $"Заполните все поля";
            return RedirectToAction("Index");

        }


        [HttpGet]
        public IActionResult Index(int? OptionId)
        {
            var viewModel = new HomeIndexViewModel();

            if (OptionId != null)
            {
                viewModel.Option = _context.Options
                    .Where(x => x.UserId == _userId || x.UserId == 0)
                    .FirstOrDefault(x => x.Id == OptionId);
            }

            viewModel.Options = _context.Options
                .Where(x => x.UserId == _userId || x.UserId == 0)
                .ToList();

            return View(viewModel);
        }

        [HttpGet]
        public IActionResult Remove(int? OptionId)
        {
            var Option = _context.Options
                .Where(x => x.UserId == _userId || x.UserId == 0)
                .FirstOrDefault(x => x.Id == OptionId);

            if (Option != null)
            {
                _context.Options.Remove(Option);
                _context.SaveChanges();

                TempData["message"] = $"Вариант {Option.Name} удален.";
            }
            else
            {
                TempData["message"] = $"Вариант не найден.";
            }

            return RedirectToAction(nameof(Index));
        }
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Teploobmen/Controllers/LoginController.cs
using Teploobmen.Data;
using Teploobmen.Models;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Security.Claims;
using TeploobmenLibrary;

namespace Teploobmen.Controllers
{
    public class LoginController : Controller
    {
        private readonly ILogger<LoginController> _logger;
        private readonly ApplicationContext _context;

        public LoginController(ILogger<LoginController> logger, ApplicationContext applicationContext)
        {
            _logger = logger;
            _context = applicationContext;
        }

        [HttpPost]
        public async Task<IActionResult> Index(string email, string password)
        {
            var user = _context.Users.FirstOrDefault(x => x.Email == email && x.Password == password);
            if (user != null)
            {
                var claims = new List<Claim> {
                    new Claim("Id", user.Id.ToString()),
                    new Claim(ClaimTypes.Name, user.Email),
                    new Claim(ClaimTypes.Role, "user"),
                };

                ClaimsIdentity claimsIdentity = new ClaimsIdentity(claims, "Cookies");

                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity));

                return RedirectToAction("Index", "Home");
            }
            return View();
        }
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();

            return RedirectToAction("Index");
        }
    }
}

Teploobmen/Controllers/RegistrController.cs
using Teploobmen.Data;
using Teploobmen.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using System.Diagnostics;
using TeploobmenLibrary;

namespace Te
    .Controllers
{
    public class RegistrController : Controller
    {
        private readonly ILogger<RegistrController> _logger;
        private readonly ApplicationContext _context;

        public RegistrController(ILogger<RegistrController> logger, ApplicationContext applicationContext)
        {
            _logger = logger;
            _context = applicationContext;
        }


        public IActionResult Index(TeploobmenInput input)
        {
            if (!string.IsNullOrEmpty(input.Email))
            {

                var user = new User
                {
                    Email = input.Email,
                    Password = input.Password,
                    //NameUser = input.NameUser
                };
                _context.Users.Add(user);
                _context.SaveChanges();
                return RedirectToAction("Index", "Home");

            }
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Teploobmen/Controllers/UserController.cs
using Teploobmen.Data;
using Teploobmen.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using TeploobmenLibrary;

namespace Teploobmen.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Teploobmen/Views/Home/Index.cshtml
@model HomeIndexViewModel
@{
    ViewData["Title"] = "Расчёт";
}
@if (!string.IsNullOrEmpty(TempData["message"]?.ToString()))
{
    <div class="alert alert-danger">
        @TempData["message"]
    </div>
}
<form action="/Home/Result" method="post">
    Номер варианта:
    <input name="Name" value="@Model.Option?.Name" autocomplete="off" data-val="true" />
    <p>
        Высота слоя (м):
        <input name="H" value="@Model.Option?.H" autocomplete="off" data-val="true" />
        Начальная температура окатышей (градусы):
        <input name="t1" value="@Model.Option?.t1" autocomplete="off" data-val="true" />
        Начальная температура воздуха (градусы):
        <input name="T" value="@Model.Option?.T" autocomplete="off" data-val="true" />
    </p>
    <p>
        Скорость воздуха на свободное сечение шахты (м/с):
        <input name="w" value="@Model.Option?.w" autocomplete="off" data-val="true" />
        Средняя теплоёмкость воздуха при 200 градусах (кДж/(кг*К):
        <input name="C" value="@Model.Option?.C" autocomplete="off" data-val="true" />
    </p>
    Расход окатышей:
    <input name="Gm" value="@Model.Option?.Gm" autocomplete="off" data-val="true" />
    Теплоёмкость окатышей:
    <input name="Cm" value="@Model.Option?.Cm" autocomplete="off" data-val="true" />
    <p><p>
        Диаметр аппарата (м):
        <input name="d" value="@Model.Option?.d" autocomplete="off" data-val="true" />
        Объемный коэффициент теплоотдачи:
        <input name="a" value="@Model.Option?.a" autocomplete="off" data-val="true" />
    </p>
    <p>
        <button type="submit"> Рассчитать</button>
    </p>
</form>
<h2>Варианты расчетов</h2>
<table class="table table-bordered">
    <tr>
        <td>Название варианта</td>
        <td>Высота слоя (м)</td>
        <td>Начальная температура окатышей (градусы):</td>
        <td>Начальная температура воздуха (градусы):</td>
        <td>Скорость вохдуха на свободное сечение шахты (м/с)</td>
        <td>Средняя теплоёмкость воздуха при 200 градусах (кДж/(кг*К)</td>
        <td>Расход окатышей:</td>
        <td>Теплоёмкость окатышей:</td>
        <td>Диаметр аппарата (м):</td>
        <td>Объемный коэффициент теплоотдачи:</td>
        <td></td>
    </tr>

    @foreach (var Option in Model.Options)
    {
        <tr>
            <td>@Option.Name</td>
            <td>@Option.H</td>
            <td>@Option.t1</td>
            <td>@Option.T</td>
            <td>@Option.w</td>
            <td>@Option.C</td>
            <td>@Option.Gm</td>
            <td>@Option.Cm</td>
            <td>@Option.d</td>
            <td>@Option.a</td>
            <td>
                <a href="/Home/Index/?OptionId=@Option.Id">Открыть</a>
                <a href="/Home/Remove/?OptionId=@Option.Id">Удалить</a>
            </td>
        </tr>

    }
</table>

Teploobmen/Views/Home/Result.cshtml
@model TeploobmenLibrary.TeploobmenOutput
@{
    ViewData["Title"] = "Расчёт";
}

@if (Model != null)
{
    <diw> <p>Площадь основания S= @Model.square</p> </diw>
    <diw> <p>Отношение теплоемкостей потоков m= @Model.relationship</p></diw>
    <diw> <p>Полная относительная высота слоя Y0= @Model.layer_height <p/> </diw>
    <h2>Таблица результатов</h2>
    <table class = "table table-bordered">
        <tr>
            <td rowspan="2">&nbsp;</td>
            <td colspan="9"> координаты y, м</td>
        </tr>
        <tr>
            @foreach (var a in Model.coordinata)
            {
                <td>@a</td>
            }
        </tr>
        <tr>
            <td> Y </td>
            @foreach (var b in Model.Y)
            {
                <td>@b</td>
            }
        </tr>

        <tr>
            <td> 1-exp(((m-1)Y)/m) </td>
            @foreach (var c in Model.exp1)
            {
                <td>@c</td>
            }
        </tr>
        <tr>
            <td> 1-m*exp(((m-1)Y)/m) </td>
            @foreach (var d in Model.exp2)
            {
                <td>@d</td>
            }
        </tr>
        <tr>
            <td> V </td>
            @foreach (var e in Model.V)
            {
                <td>@e</td>
            }
        </tr>
        <tr>
            <td> O </td>
            @foreach (var f in Model.O)
            {
                <td>@f</td>
            }
        </tr>
        <tr>
            <td> t окатышей </td>
            @foreach (var g in Model.t)
            {
                <td>@g</td>
            }
        </tr>
        <tr>
            <td> T пара </td>
            @foreach (var h in Model.T)
            {
                <td>@h</td>
            }
        </tr>
        <tr>
            <td> Разность температур </td>
            @foreach (var i in Model.t_T)
            {
                <td>@i</td>
            }
        </tr>
    </table>

    <div class="Chart">
        <canvas id="myChart"></canvas>
    </div>

    <script src="/js/chart.js"></script>

    <script>
        const ctx = document.getElementById('myChart');

        const data = {
            labels: @Json.Serialize(Model.coordinata),
            datasets: [
                {
                    label: 'Температура металла',
                    data: @Json.Serialize(Model.t),
                },
                {
                    label: 'Температура газа',
                    data: @Json.Serialize(Model.T),
                },
                {
                    label: 'Разность температур',
                    data: @Json.Serialize(Model.t_T),
                }
            ]
        };

        const configLine = {
            type: 'line',
            data: data,
            options: {
                responsive: true,
                plugins: {
                    legend: {
                        position: 'top',
                    },
                    title: {
                        display: true,
                        text: 'График'
                    }
                }
            },
        };
        new Chart(ctx, configLine);
    </script>
}

Teploobmen/Views/Login/Index.cshtml
@model HomeIndexViewModel
@{
    ViewData["Title"] = "Расчёт";
}

<form action ="/Login"method="post">
    Email:
    <input name="Email" value="" autocomplete="off" />
    Пароль:
    <input type="password" name="Password" value="" autocomplete="off" />

    <button type="submit"> Войти</button>
</form>

Teploobmen/Views/Registr/Index.cshtml
@model TeploobmenLibrary.TeploobmenInput
@{
    ViewData["Title"] = "Регистрация";
}

<form action="/Registr" method="post">
    Введите свой Email:
    <input name="Email" value="" autocomplete="off" />
    Введите пароль:
    <input type="password" name="Password" value="" autocomplete="off" />
    <button type="submit"> Зарегистрироваться</button>
</form>

Teploobmen/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Teploobmen</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/labwork2_web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Teploobmen</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Расчёт</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Logout">Выход</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User">Личный кабинет</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Login">Авторизация</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Registr" asp-action="Index">Регистрация</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Teploobmen - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Teploobmen/Views/User/Index.cshtml
@model HomeIndexViewModel
@{
    ViewData["Title"] = "Home Page";
}

<div>Привет, @User.Identity.Name!</div>